# Generated by Django 6.1.1 on 2026-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
    ]
